### ISSUE TITLE
Set resolution

### ISSUE THREAD

**Issue by bonjour81** [closedcube/ClosedCube_HDC1080_Arduino#1]
Hello,
it seems that measurement resolution is set to minimum (8bit for H, 11bit for T).
Examples does not show how to set better resolution.
It would be great to add this to examples.
Best regards,

**Comment by nissimzur** [comment]
Just open the HDC1080 data sheet and see the register setting. 
http://www.ti.com/lit/ds/symlink/hdc1080.pdf

Kind regards,
Dr. Nissim Zur
Bluetooth Smart, IoT expert
Skype: nissim.test

**Comment by bonjour81** [comment]
Hello, 
it's not the point to read the datasheet, it's already done and I can modify the lib to add the value I want as defaut value for resolution.
But I'm a bit new in arduino and I cannot figure out how to set the resolution using the normal way (without modifying the lib itself). I guess there is a function for that in the library.


And, most important, it's a little bit a pity to setup an example that does not show this. 
I can only speak for myself but with an example, 3 seconds later you know how to do, without, it can be some hours to understand how the functions in the lib are supposed to work.

Anyway, that's just a suggestion to improve the provided example.

**Comment by closedcube** [comment]
Hello,

Thank you for your suggestions.

We will review these examples and will try to add additional info for the default values.

Best regards,
ClosedCube

**Comment by closedcube** [comment]
**Default settings:** 
-  Heater off
- 14 bit Temperature and Humidity Measurement Resolutions

**Comment by closedcube** [comment]
The library has two option to change measurement resolutions:

1.  using 'setResolution' (generic) 
2.  using 'writeRegister' (low-level)
