### ISSUE TITLE
HDC1080 returns always 125C degree temperature

### ISSUE THREAD

**Issue by z4nD4R** [closedcube/ClosedCube_HDC1080_Arduino#11]
Hello, 

I'm using the given library in my own project where I've built my own lib (inherit from parrent one). The ClosedCube lib works fine - the test are finished just fine.

Unfortunately when I use it in my own lib, the ClosedCube lib returns always 125C as measured temp. The humidity looks like measured in proper way.

I'm attaching also the snipped of the code:

```
jGPHT::jGPHT(String id, int defaultUpdateInterval):MyDevice(id, defaultUpdateInterval),ccs(CCS811_ADDR),hdc1080(),myBME280()
{
    // Init HDC
    hdc1080.begin(0x40);
   returnCode = returnCode +" "+ (String)hdc1080.readDeviceId(); // 0x5449 ID of Texas Instruments
}

String jGPHT::status()
{
  temp = 0;
  hum = 0;
  hum = (float)hdc1080.readHumidity();
  temp = (float)hdc1080.readTemperature();
  Serial.println(temp); // prints 125 all the time
  Serial.println(hum); // looks like printing correct value
}
```

I'd appreciate any help or advice.

Thank you.

Y

**Comment by z4nD4R** [comment]
Hello,

anybody alive?

Y

**Comment by z4nD4R** [comment]
Hi, 

it looks like the same issue. Did you figure it out?

Y

**Comment by bfaliszek** [comment]
Not yet. I have HDC1080 only for a few days. I have HDC1080 on a PCB board together with CCS811 (TVOC and CO2 sensor). 

![d61f1742-3e23-4bd8-b9b3-66b0f9236f6e](https://user-images.githubusercontent.com/1752244/51031627-79dbaf80-159d-11e9-8df0-8ea23cf10a8b.JPG)

**Comment by z4nD4R** [comment]
Yeah, I have the same board. You will have also lot of "fun" with Co2 :D

**Comment by bfaliszek** [comment]
CO2 sensor works well. I use this library - https://github.com/maarten-pennings/CCS811 and uploaded a firmware on the sensor: https://github.com/maarten-pennings/CCS811/tree/master/examples/ccs811flash

**Comment by z4nD4R** [comment]
Yeah Co2 works ok, but for me sometime it goes crazy like 7000ppm.
Btw, did you figured out whats wrong with HDC1080 temperature?

**Comment by bfaliszek** [comment]
@z4nD4R here is an explanation of how CCS811 works: https://github.com/maarten-pennings/CCS811/issues/8#issuecomment-451936735

In the HDC1080 topic, for a few days I used the example from the Texas Instruments website (HDC1080 Arduino Example Code v1.0 - http://www.ti.com/product/HDC1080/toolssoftware). The temperature measurements were correct and there was no problem with 125C. However, the humidity readings were very strange. They hardly changed at all. Compared to the data from BME280, they did not make any sense.

**Comment by antoniosap** [comment]
```
T 125.0 H 100
ID=0xFFFF
```

**Comment by pashar1** [comment]
have anyone resolved it ?

**Comment by spdi** [comment]
I had the same issues. The ClosedCube lib returned always 125C as measured temperature, but humidity was fine. Also CCS811 always returned all bytes as 0xFFFF.

My solution is to add wire initialisation as simple as:
`Wire.begin(SDApin, SCLpin);`

then init particular sensors as library documentation states.

**Comment by ramiws** [comment]
I have HDC1080 on a PCB board together with CCS811  too. 
All works good except that temp from HDC1080 is few degrees higher than the correct value! Is it damaged? did I damage it during soldering pins ? it is now 25.4 but it shows 28.1

**Comment by ybatuto** [comment]
Got the same 125 degrees. 
I fixed it by changing delay(10) to delay(20) like it recommended in TI example.

**Comment by panicacid** [comment]
I'm having the same issue, I've got 3 x HDC1080's connected to a TCA9548A and sensor 1 and 2 give me the right RH and Temp readings however sensor 0 gives me 125c for temp and then the correct RH. Tried swapping the sensor and even adding delays in the reading aspect:

22:59:29.328 -> Publishing on topic Wineador/Temp/Top at QoS 1, packetId: 0Message: 124.997 
22:59:29.396 -> Publishing on topic Wineador/RH/Top at QoS 1, packetId: 0Message: 51.569 
22:59:29.462 -> Publishing on topic Wineador/Fault/Top at QoS 1, packetId: 0Message: 1.756 
22:59:29.565 -> Publishing on topic Wineador/Temp/Mid at QoS 1, packetId: 0Message: 19.941 
22:59:29.631 -> Publishing on topic Wineador/RH/Mid at QoS 1, packetId: 0Message: 59.705 
22:59:29.698 -> Publishing on topic Wineador/Fault/Mid at QoS 1, packetId: 0Message: 1.756 
22:59:29.799 -> Publishing on topic Wineador/Temp/Bot at QoS 1, packetId: 0Message: 19.861 
22:59:29.865 -> Publishing on topic Wineador/RH/Bot at QoS 1, packetId: 0Message: 60.333 
22:59:29.932 -> Publishing on topic Wineador/Fault/Bot at QoS 1, packetId: 0Message: 1.756 

code for reading below - I'm publishing them to a MQTT broker so excuse the padding around the key bit.
setup:

  tcaselect(2);

  hdc1080.begin(0x40);

Loop
    // Read & Publish Sensor 0 Values (Top)

    tcaselect(2);
delay(20);
    TopRH = hdc1080.readHumidity();
delay(20);
    TopTemp = hdc1080.readTemperature();
delay(20);
    if (TopRH >= 99.9) {

      TopFault = 1; // sets our Fault integer to 1 which is the number node red is looking for on this payload to know theres a Fault, 0 = no Fault 1 = Fault.

      // Publish an MQTT message about failure
      uint16_t packetIdPub6 = mqttClient.publish(MQTT_PUB_FAULT_TOP, 1, true, String(TopFault).c_str()); // Publish an MQTT message about failure
      Serial.printf("Publishing on topic %s at QoS 1, packetId: %i", MQTT_PUB_FAULT_TOP, packetIdPub6);
      Serial.printf("Message: %.3f \n", TopFault);
    }

    else

    {

      TopFault = 0; // Sets our Fault integer to 0 which lets Node Red know everything is gravy.

      uint16_t packetIdPub4 = mqttClient.publish(MQTT_PUB_TEMP_TOP, 1, true, String(TopTemp).c_str()); // This string sends our temp data to Node Red
      Serial.printf("Publishing on topic %s at QoS 1, packetId: %i", MQTT_PUB_TEMP_TOP, packetIdPub4);
      Serial.printf("Message: %.3f \n", TopTemp);

      uint16_t packetIdPub5 = mqttClient.publish(MQTT_PUB_RH_TOP, 1, true, String(TopRH).c_str()); // This string sends our RH data to Node Red
      Serial.printf("Publishing on topic %s at QoS 1, packetId: %i", MQTT_PUB_RH_TOP, packetIdPub5);
      Serial.printf("Message: %.3f \n", TopRH);

      uint16_t packetIdPub6 = mqttClient.publish(MQTT_PUB_FAULT_TOP, 1, true, String(TopFault).c_str()); // This string sends our Fault data to Node Red
      Serial.printf("Publishing on topic %s at QoS 1, packetId: %i", MQTT_PUB_FAULT_TOP, packetIdPub6);
      Serial.printf("Message: %.3f \n", TopFault);
    }

**Comment by djdunc** [comment]
@panicacid I am seeing the same issue - 5 HDC1080 sensors connected to TCA9548A but only the first on address 0 reporting 125. Did you find a fix?

**Comment by djdunc** [comment]
update - i changed the delay before the sensor read to delay(20); and is now working. I originally had delay(50);

**Comment by marcelrv** [comment]
@ramiws 
> I have HDC1080 on a PCB board together with CCS811 too.
> All works good except that temp from HDC1080 is few degrees higher than the correct value! Is it damaged? did I damage it during soldering pins ? it is now 25.4 but it shows 28.1

I have the same. Did you find a fix for that? It is approx 3 degrees more than the real temperature. I have 2 sensors, with both same problem, they give near identical responses (few 10th difference between the 2)

**Comment by sebastian-ksk** [comment]
hi,
for the one with the same error, this is solved by restarting the sensors through 
sensor.begin ();
for all sensors

**Comment by clupinos** [comment]
> hi,
> for the one with the same error, this is solved by restarting the sensors through
> sensor.begin ();
> for all sensors

You save my day! Thanks a lot!!

**Comment by gabrielgisbert** [comment]
Hi!
I had same problem. In my particular case, but it seems like yours, sensor gives you always 125 degrees (max temp) because of the input voltage you use to power it. 
It could be that you are using more than 5v
To solve it, first of all (with a voltimeter) you have to read input voltage, if you are using 5 or more than 5 volts, thats the problem!
In my case I was using 6v from a battery made by 4 1.5v batteries. After that, I removed one of  them, and the new voltage was 4.5v and it works perfectly.

Good luck!

**Comment by SovGVD** [comment]
Hello there, sorry for reopening (feel free to close).
Never buy HDC1080 + CCS811 board, as soon as you activate CCS811, the temperature value on HDC1080 going up and humidity going down. One of the solution is to disable heating (???) for CCS811 by set `ccs811.setDriveMode(CCS811_DRIVE_MODE_IDLE);` after measure, you will see how values of HDC1080 slowly returning to normal.

Good luck!

**Comment by Drakot** [comment]
i couldn't make it work, using all your fixes it stays with 125º and 100% humidity. I thought it was the pins on my ESP8266, buy I recheck like 6 times and they are ok. I checked the voltage with a voltimeter and everything is receiving current. So I guess my HDC1080 is damaged or something

**Comment by Olejan** [comment]
To solve 125 degrees problem I used `Wire.begin();` code before `hdc1080.begin(0x40);` in `setup()` function without any delay before temperature and humidity reading

**Comment by vinimlo** [comment]
Had the same issue! I solved using a pin to serve as the positive input, getting all the correct readings now!

**Comment by yassenb** [comment]
You can try the resolution in my last comment here: https://github.com/closedcube/ClosedCube_HDC1080_Arduino/issues/13

**Comment by thiagosanches** [comment]
Hi everyone, same problem here with the EXACTLY sensor on a esp32.

**Comment by thiagosanches** [comment]
> 

Can you give me an example?

**Comment by thiagosanches** [comment]
Oh, actually I was able to make the change that you guys said, and that worked. So, changing the `delay(9)` to `delay(20)` resolved the issue.
