### ISSUE TITLE
Serial ID

### ISSUE THREAD

**Issue by joseitor** [closedcube/ClosedCube_HDC1080_Arduino#3]
It would be great if you could add a function to read serial IDs from the sensor. 
According the datasheet, it has a serial ID formed by 5 bytes (2+2+1).
I think it is a easy work for you, but hard for me. If you could make it I would be very glad.

**Comment by fusionstream** [comment]
I'm curious. What was the need for this? Were you able to stack multiple HDC1080s on the same i2c address because of this?

**Comment by Veoramid** [comment]
Hello. My program crashed. Searched for two weeks with me. But there was a problem in the code:
char format[**12**];
	sprintf(format, "**%02X-%04X-%04X**", sernum.serialFirst, sernum.serialMid, sernum.serialLast);
	
**12** is not enough for "**%02X-%04X-%04X**". I lost two weeks. Helped on the forum arduino.ru user **sadman41**. Thanks to him!
